- name: Create folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', 'templates/folder.xml') }}"
    name: "{{item}}"
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"
  loop: "{{ folders }}"


- name: create mbranch jobs
  ansible.builtin.include_tasks: "mbranch-pipeline.yml"
  loop: "{{ ci_pipeline_jobs }}"

- name: create sbranch jobs
  ansible.builtin.include_tasks: "sbranch-pipeline.yml"
  loop: "{{ sbranch_pipeline_jobs }}"