- name: copy config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: test
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"