- name: copy {{item.name}} config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job-{{item.name}}.xml

- name: Create {{item.name}} job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job-{{item.name}}.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"
