- name: copy config file
  ansible.builtin.template:
    src: folder.xml
    dest: /tmp/folder.xml

- name: Create folder {{item.dir}}
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/folder.xml') }}"
    name: "{{item.dir}}"
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"


- name: copy config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"
