- name: CHeck if jobs already exists
  ansible.builtin.shell: java -jar /opt/jenkins-cli.jar -auth admin:{{jenkins_password}} -s http://172.31.32.110:8080 -webSocket get-job {{item.dir}}/{{item.name}}
  register: out
  ignore_errors: yes

- name: copy {{item.name}} config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  when: out.rc == 3

- name: Create {{item.name}} job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.rc == 3
