- name: check if job exists or not
  community.general.jenkins_job_info:
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"
    name: "{{item.dir}}/{{item.name}}"
  register: out
  ignore_errors: yes

- name: copy {{item.name}} config file
  ansible.builtin.template:
    src: s-job.xml
    dest: /tmp/s-job.xml
  when: out.failed | bool

- name: Create {{item.name}} job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/s-job.xml') }}"
    name: "{{item.dir}}/{{item.name}}"
    url: http://172.31.32.110:8080
    user: admin
    password: "{{jenkins_password}}"
  when: out.failed | bool
